### PR TITLE
support composite tags

### PR DESCRIPTION
**Pull request by Bertk**
- support SpecSync for MTM see
https://gasparnagy.gitbooks.io/specsync-for-mtm-documentation/content/linking-work-items-with-tags.html

### CODE REVIEW

**Comment by racodond** [comment]
Thanks for the PR @Bertk!
I'll have a look at it as soon as I can.

**Comment by racodond** [comment]
@Bertk: My apologies for the late feedback... 
So, basically, you just want to make the parameter of rule 'allowed-tags' a regular expression, right?
Could you please move the pull request on branch Bertk? I'll tune what you've already done and make you review it before merging.

Thanks!

**Comment by Bertk** [comment]
@racodond Hi,
Great - is there a simple way to move the PR to the bertk branch or should I create a new PR and close this one? Sorry,  am not a git expert.

**Comment by Bertk** [comment]
Created new PR #62 
I do not have permission to push to branch racodond:Bertk

**Pull request closed without merging**
